<!--/#bottom-->
    
    <section id="bottom">
        <div class="container wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="row">
            
            <div class="col-md-3 col-sm-6">
                    <div class="widget" style="color:#808080;">
                      <h3>Reach Us</h3>
                        <ul>
                            <li>
                           <B> Hello42 India Pvt. Ltd</B><br />
29-30, D.B Gupta Market, Karol Bagh,<br /> New Delhi - 110005 (India)
  
                            
                            </li>
                            <li>
                            <b>Tel : </b><br />
                           	+91 11 42424242</li>
                            <li>
                           <b> E-mail</b><br />
                            	feedback@hello42cab.com  

                            
                            </li>
                                                    </ul>
                    </div>    
                </div><!--/.col-md-3-->
            
            
             
            
                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3>Company</h3>
                        <ul>
                            <li><a href="index/page/about_us">About us</a></li>
                            <li><a href="index/page/career">We are hiring</a></li>
                           <!-- <li><a href="index/page/about_us#feature">Meet the team</a></li>-->
                            <li><a href="index/page/copyright">Copyright</a></li>
                            <li><a href="index/page/terms_condition">Terms of use</a></li>
                            <li><a href="index/page/privacy_policy">Privacy policy</a></li>
                            <li><a href="index/page/contact_us">Contact us</a></li>
                        </ul>
                    </div>    
                </div><!--/.col-md-3-->

                <div class="col-md-2 col-sm-6">
                    <div class="widget">
                        <h3>Support</h3>
                        <ul>
                            <li><a href="index/page/faq">Faq</a></li>
                           <!-- <li><a href="index/page?id=blog">Blog</a></li>-->
                            <!--<li><a href="#">Forum</a></li>-->
                            <li><a href="index/page/documettion">Documentation</a></li>
                            <li><a href="index/page/refund_policy">Refund policy</a></li>
                            <li><a href="index/page/ticket_system">Ticket system</a></li>
                            <li><a href="index/page/billing_system">Billing system</a></li>
                        </ul>
                    </div>    
                </div><!--/.col-md-3-->

               <div class="col-md-4 col-sm-6 col-sm-61">
                    <div class="widget">
                        <h3>Testimonials</h3>
                      
                        
                        <div class="col-md-1 col-lg-12 img-responsive" 
                        style="margin-top:0; overflow:hidden; padding:0;" id="slider1">
  <div id="myCarousel1" class="carousel slide" data-ride="carousel" 
  style="height:225px; overflow:hidden; background:transperent !important;"> 
    <!-- Indicators -->
    <ol class="carousel-indicators" style="display:block; margin-bottom:-20px !important;">
      <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel1" data-slide-to="1" class=""></li>
      <li data-target="#myCarousel1" data-slide-to="2" class=""></li>
     <li data-target="#myCarousel1" data-slide-to="3" class=""></li>
       <!--<li data-target="#myCarousel1" data-slide-to="4" class=""></li>-->
    </ol>
    <div class="carousel-inner">
      <div class="item active" id="" style="background:#000;">  
      					<ul>
      
                            <li>
                            <div class="col-xs-12 col-sm-12 wow fadeInDown">
                    <div class="testimonial">
                       
                         <div class="media testimonial-inner">
                            <div class="pull-left">

					<label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                               <!-- <img class="img-responsive img-circle" src="<?php echo $this->basePath();  ?>/public/images/testimonials1.png">-->
                            </div>
                            <div class="media-body">
                                <p>Hello42Taxi has reduced our stress and allowed us to develop more 
                                business, with less time spent managing it, on click access to all 
                                available cabs is unbelievable as it takes only few minutes to get a cab, Cheers to Hello42Taxi.</p>
                                <span><strong>-Abhishek Gupta</strong></span>
                            </div>
                         </div>

                         

                    </div>
                </div></li>
                    
                        </ul>
        
      </div>
      
      <div class="item" style="background:#000;"> 
      <ul>
      
                            <li><div class="col-xs-12 col-sm-12 wow fadeInDown">
                    <div class="testimonial">
                       
                         <div class="media testimonial-inner">
                            <div class="pull-left">
						<label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                            </div>
                            <div class="media-body">
                                <p>We've never seen any platform that exclusively made for tour operators 
                                to connect us online. Hello42Taxi has solved the problem faced by 
                                ssthousands of tour operators. It's really easy to use and cost efficient.</p>
                                <span><strong>-Mukesh/</strong> Viva</span>
                               
                                
                            </div>
                         </div>

                         

                    </div>
                </div></li>
                    
                        </ul>
       
      </div>
      
      <div class="item" style="background:#000;"> 
      <ul>
      
                            <li><div class="col-xs-12 col-sm-12 wow fadeInDown">
                    <div class="testimonial">
                       
                         <div class="media testimonial-inner">
                            <div class="pull-left">
                                <label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                            </div>
                            <div class="media-body">
                                <p>We had a great experience with Hello42cab, the car 
                                was arranged within 30 mins - that too on a busy Monday morning. 
                                Awesome!</p>
                                <span><strong>-arvind Goswami</strong> </span>
                            </div>
                         </div>

                         <div class="media testimonial-inner">
                            <div class="pull-left">
                               <label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                            </div>
                            <div class="media-body">
                                <p>Extremely good and keep it up.</p>
                                <span><strong>-Mayank Agarwal</strong></span>
                            </div>
                         </div>

                    </div>
                </div></li>
                    
                        </ul>
        
      </div>
      
      <div class="item" style="background:#000;"> 
      <ul>
      
                            <li><div class="col-xs-12 col-sm-12 wow fadeInDown">
                    <div class="testimonial">
                       
                         <div class="media testimonial-inner">
                            <div class="pull-left">
                                <label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                            </div>
                            <div class="media-body">
                                <p>Hello42 cabs customer service is very nice. Booked me a very comfortable ride to Delhi from Agra!</p>
                                <span><strong>-Ajay Kohli</strong> </span>
                            </div>
                         </div>

                         <div class="media testimonial-inner">
                            <div class="pull-left">
                               <label style="background:#333; border-radius:50%; padding:8px 20px; font-size:40px;">                           
					<i class="fa fa-user" aria-hidden="true"></i>
					</label> 
                            </div>
                            <div class="media-body">
                                <p>The cab came on time to the airport & was very reasonably priced.</p>
                                <span><strong>-Neelam Oberoi</strong> </span>
                            </div>
                         </div>

                    </div>
                </div></li>
                    
                        </ul>
        
      </div>
      
    </div>
  </div>
</div>
                    </div>    
                </div>
                
                
                
                <!--/.col-md-3-->

                
            </div>
        </div>
    </section>

	 
    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    Copyright &copy; 2013 <a target="_blank" href="#" title="RegencyTours">Helle42 Cab Pvt. Ltd.</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
        <p style="text-align:right;">
    	 <a class="btn btn-social-icon padding_margin0" target="_blank" href="https://www.facebook.com/hello42indiapvtltd/"><i class="fa fa-facebook fa-1x socialneticons btn-danger"></i></a> 
         <a class="btn btn-social-icon padding_margin0" target="_blank" href="https://twitter.com/Hello42Cab"><i class="fa fa-tumblr fa-1x socialneticons btn-danger"></i></a> 
         <a class="btn btn-social-icon padding_margin0" target="_blank" href="https://www.linkedin.com/in/hello42cab/"><i class="fa fa-linkedin fa-1x socialneticons btn-danger"></i></a> 
         <a class="btn btn-social-icon padding_margin0" target="_blank" href="https://plus.google.com/u/0/"><i class="fa fa-google-plus fa-1x socialneticons btn-danger"></i></a> 
        </p>
    
    </div>
        </div>
        
        </div>
    </footer><!--/#footer-->

  <!-- City selection print sms start-->

<div class="modal fade" id="myModalprintsmscancle" role="dialog">
    <div class="modal-dialog modal-dialogprint">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title">

Print/SMS Booking

</h2>
        </div>
        <div class="modal-body">
          <div class="row" style="padding:0 15px;">
                   
          <div class="col-sm-12 price-one ">
          
         <!-- <div class="col-lg-12" style=" background: #c52d2f none repeat scroll 0 0; color: #fff; padding:5px;">
           <h2>Package-
                                <span style="font-size:14px;">4 Hours - 40 KM</span>
                                </h2></div>-->
          
          <div class="col-lg-12" style="background:#EFEFEF;">
           <label class="col-lg-12 padding0" style="text-align:left; color:#000;"> Booking No.  </label> 
          	<input class="form-control" placeholder="Ticket No." style="border:1px solid #333;">
          
            <label class="col-lg-12 padding0" style="color:#000;">
            Mobile No.
             </label>
           
           <input class="form-control" placeholder="Mobile No." style="border:1px solid #333;">
            
             
             <label class="col-lg-12" style="color:#000; text-align:right; margin-top:5px;">
                                <a href="#topheader" class="btn btn-primary"  role="button" id="local" onclick="booking_local();">Submit</a>
                           
                           </label>
            
          </div>
          
           
                      
                            
            
                                 </div>
                          
          </div>
          
        </div>
        <div class="modal-footer" style=" padding-top:2px !important;">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
  <!-- City selection print sms ends--> 
    
    <div class="modal fade" id="myModalfeedbackss" role="dialog">
    <div class="modal-dialog  modal-dialogfeedback">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title">

			Feedback
			</h2>
					<!--Click to select if we Exceeded, Met or Did Not meet your Expectations-->
        </div>
       
<style type="text/css">
    .box{
       
        display: none;
       
        
    }
   
</style>
        <?=$this->serverurl().$this->url();
        echo $_SERVER['PHP_SELF'];
        ?>
        <form id="feedbackform" method="post" autocomplete="off" action="<?php echo $this->basePath();  ?>/index/page/feedback"  onsubmit="return validfeedform(this.id);">
        <div class="modal-body" style="height:500px; overflow:scroll;">
          <div class="row" style="padding:0 15px;">
                   
          <div class="col-sm-12 plan price-one " style="background:#EFEFEF;">

          
         
          	<div class="col-lg-12 feedback">
          
           <label class="col-sm-12" style="text-align:left;"> 
          1. RESERVATION:- </label> 
           
            <div class="col-sm-3" >
          	Reservation is done through
          
          </div>
          
           <div class="col-sm-3" >
          	<input type="radio" name="resersvation" value="1"/> Website 
          
          </div>
          
           <div class="col-sm-3" >
          	<input type="radio" name="resersvation" value="2" /> Android Application
          
          </div>
          
           <div class="col-sm-3" >
          	<input type="radio" name="resersvation" value="3"/> Call Center
          
          </div>
          
           
           
           </div>
          
          <div class="box website" style="display:block;">
          <div class="col-lg-12 feedback">
           <label class="col-sm-12" style="text-align:left;"> 
          <strong> Website</strong>  </label> 
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the booking process 
          </label>
          </div>
          
          <div class="col-sm-6" >
          	<label class="col-sm-3"><input type="radio" value="bad" name="web_booking_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="web_booking_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="web_booking_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="web_booking_rate" />Very Good</label>
          
          </div>
          
          
          
          
           
           
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the confirmation process
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="web_confirm_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="web_confirm_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="web_confirm_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="web_confirm_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	Rate the process on website 
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="web_process_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="web_process_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="web_process_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="web_process_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	Over all how would you rate our services
          </label>
          </div>
          
           <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="web_service_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="web_service_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="web_service_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="web_service_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           </div>
           
           <div class="box mobileaap">
          <div class="col-lg-12 feedback">
           <label class="col-sm-12" style="text-align:left;"> 
           <strong>Android Application</strong>  </label> 
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate our App  
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="And_app_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="And_app_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="And_app_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="And_app_rate" />Very Good</label>
          
          </div>
          
          
          
          
          
           
           
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the booking process
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="And_book_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="And_book_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="And_book_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="And_book_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the confirmation process 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="And_confirm_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="And_confirm_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="And_confirm_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="And_confirm_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	Over all how would you rate our services
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="And_service_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="And_service_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="And_service_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="And_service_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           </div>
           
                      
           <div class="box callcenter">
          <div class="col-lg-12 feedback">
           <label class="col-sm-12" style="text-align:left;"> 
           <strong>Call Center </strong>  </label> 
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the booking process 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="Call_book_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="Call_book_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="Call_book_rate" /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="Call_book_rate" />Very Good</label>
          
          </div>
          
          
          
          
           
           
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate  our agent  to answer your question
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="Call_agent_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="Call_agent_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="Call_agent_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="Call_agent_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate our  agent to follow your instructions 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="Call_instruc_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="Call_instruc_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="Call_instruc_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="Call_instruc_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the confirmation process 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="Call_confirmation_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="Call_confirmation_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="Call_confirmation_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="Call_confirmation_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	Over all how would you rate our services   
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="Call_services_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="Call_services_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="Call_services_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="Call_services_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           </div>
           
           
           
           <div class="col-lg-12 feedback">
          
           <label class="col-sm-12" style="text-align:left;"> 
          2. VEHICLES:- </label> 
          
          </div>
           
           <div class="">
          <div class="col-lg-12 feedback">
         
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the reporting of vehicle 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="vehicle_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="vehicle_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="vehicle_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="vehicle_rate" />Very Good</label>
          
          </div>
          
          
          
          
           
           
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate the vehicle as requested
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="requested_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="requested_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="requested_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="requested_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How was your special instructions followed 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="insfollow_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="insfollow_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="insfollow_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="insfollow_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How was the vehicle condition
          </label>
          </div>
          
           <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="condition_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="condition_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="condition_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="condition_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How was the Air-Conditioning effective
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="effective_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="effective_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="effective_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="effective_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How was the cleanness and tidy of vehicle 
          </label>
          </div>
          
          <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="cleanness_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="cleanness_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="cleanness_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="cleanness_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How Was the uniform and grooming
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="grooming_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="grooming_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="grooming_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="grooming_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
           </div>
           
             <div class="col-lg-12 feedback">
          
           <label class="col-sm-12" style="text-align:left;"> 
          2. BILLING:- </label> 
          
          </div>
           
           <div class="">
          <div class="col-lg-12 feedback">
         
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate  the billing accuracy 
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="accuracy_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="accuracy_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="accuracy_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="accuracy_rate" />Very Good</label>
          
          </div>
          
          
          
          
           
           
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How do you rate receiving  invoice on time
          </label>
          </div>
          
           <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="invoice_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="invoice_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="invoice_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="invoice_rate" />Very Good</label>
          
          </div>
          
          
          
           </div>
           
           <div class="col-lg-12 feedback">
          
            <div class="col-sm-5" >
            <label class="col-sm-12">
          	How will you rate your receiving invoice 
          </label>
          </div>
          
         <div class="col-sm-6" >
            <label class="col-sm-3"><input type="radio" value="bad" name="receivingInv_rate" /> bad </label>
            <label class="col-sm-3"><input type="radio" value="Average" name="receivingInv_rate" /> Average </label>
           <label class="col-sm-3"> <input type="radio" value="Good" name="receivingInv_rate"  /> Good</label>
           <label class="col-sm-3"> <input type="radio" value="Very Good" name="receivingInv_rate" />Very Good</label>
          
          </div>
          
          
           </div>
           
      
           
           </div>
           
           
            
              <div class="col-sm-8">
             
            
          </div>
          
          <div class="col-sm-4">
             <label class="col-lg-12" style="color:#000; text-align:center;">
                                <!-- <a href="#topheader" class="btn btn-primary"  role="button" id="local" onclick="booking_local();">Submit</a> -->
                                <input type="submit" value="submit" name="submit" class="btn btn-primary">
                           
                           </label>
            
          </div>
          
          
          
           
                      
                            
            
                                 </div>
                          
          </div>
          
        </div>
      </form>
        <div class="modal-footer" style=" padding-top:2px !important;">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
    
  <!----login----->
  
  <div class="modal fade" id="myModallsogin" role="dialog">
    <div class="modal-dialog modal-dialoglogin">
    
      <!-- Modal content-->
      <div class="modal-content modal-dialoglogin1 login_form">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title">

Login

</h2>
        </div>
        <div class="modal-body">
          <div class="row" style="padding:0 15px;">
                   
          <div class="col-sm-12 price-one ">
          
         <!-- <div class="col-lg-12" style=" background: #c52d2f none repeat scroll 0 0; color: #fff; padding:5px;">
           <h2>Package-
                                <span style="font-size:14px;">4 Hours - 40 KM</span>
                                </h2></div>-->
          <form id="login_form2" autocomplete="off">
          <div class="col-sm-6" style="border-right:1px solid #ccc;">
          
          <p class='invalid' style='display:none;color:red'>Invalid Username or Password</p>
           <label class="col-lg-12" style="text-align:left;"> Email or Mobile  </label> 


          	<input class="form-control"  id="login_email" name="login_email" placeholder="Email or Mobile">
          
            <label class="col-lg-12" style="color:#000;">
            Password
             </label>
      
           <input class="form-control" type="password" id="login_password" name="password" placeholder="Password">
            
             
             <label class="col-lg-12" style="color:#000; text-align:center; margin-top:5px;">
             <input type="button" id="signin"   value="Login" class="btn btn-primary"  />
                      
                           </label>
            <label>
             <a href="#" id="forgot_form" class="loginhome"> Forgot password?</a><br />

 <a href="<?php echo $this->basePath(); ?>/login/index/signup" class="loginhome">New User? Create Account </a>
            </label>
            <label class="col-lg-12" style="color:#000;"></label>
            <div align="center"> OR</div>
            <label class="col-lg-12" style="color:#000;"></label>
            
            <div class="col-md-12" id="renderMe" style="padding:0 !important;" >
            <a class="btn btn-danger btn-social btn-google-plus" style="background:#c52d2f; color:#fff;">
							<i class="fa fa-google-plus"></i>Sign in with Google Plus
						  </a></div>
                          
                     <label class="col-lg-12" style="color:#000;"></label>     
                          <div class="col-md-6" id="renderMe" align="left" style="padding:0 !important;">
							 <a class="btn btn-danger btn-social btn-google-plus" style="background:#3c55a2; color:#fff;">
							<i class="fa fa-facebook  fa-1x"></i>
                            
                            Connect using Facebook
						  </a>
                          
                         
                            </div>
                             <label class="col-lg-12" style="color:#000;"></label>
						    <div class="spance col-md-6">
								<script type="in/Login">
								</script>
								</div>
            
          </div>
          </form>
          <div class="col-sm-5 right" style="float:right;" align="right">
           <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="<?php echo $this->basepath(); ?>/login/index/myaccount" class="loginhome">My Profile </a> </label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="<?php echo $this->basepath(); ?>/login/index/myaccount" class="loginhome">Manage Bookings</a>
    </label>
    <label class="col-lg-12" style="border-bottom:1px solid #ccc;"></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
   <a href="#" class="loginhome"> View E-Ticket</a></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
   <a href="#" class="loginhome"> Cancel Bookings</a></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="#" class="loginhome">Change Travel Date</a></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="#" class="loginhome">Check Refund Status</a></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="#" class="loginhome">View Holiday Booking</a></label>
    <label class="col-lg-12" style="padding-right:0 !important;"> 
    <a href="#" class="loginhome">Make Payment</a></label>
  
          	
            
          </div>
          
           
                      
                            
            
                                 </div>
                          
          </div>
          
          <div></div>
          
        </div>
        
        
        <div class="modal-footer" style=" padding-top:2px !important;">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
      
      <div class="modal-content modal-dialoglogin2 modal-dialoglogin1 forgot_form" style="display:none;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h2 class="modal-title">

Forgot Pasword

</h2>
        </div>
        
        
        <div class="modal-body">
          <div class="row" style="padding:0 15px;">
                   
          <div class="col-sm-12 plan price-one ">
          
         <!-- <div class="col-lg-12" style=" background: #c52d2f none repeat scroll 0 0; color: #fff; padding:5px;">
           <h2>Package-
                                <span style="font-size:14px;">4 Hours - 40 KM</span>
                                </h2></div>-->
         <form id="login_form4" novalidate>
          <div class="col-sm-12">
          
          <p class='invalid' style='display:none;color:red'>Invalid Username or Password</p>
           <label class="col-lg-12" style="text-align:left;"> Enter your email to Reset Password  </label> 
           
           <input  type="text" id="email" name="login_email" placeholder="Type your email here" class="form-control">

                       
             <label class="col-lg-12" style="color:#000; text-align:center; margin-top:5px;">
            
               <a href="#" class="btn btn-primary back_btn"><i class="fa fa-angle-double-left"></i> Back</a>
                               
             <input type="button" id="forget" value="Submit" class="btn btn-primary">
                      
                      
                   
                           </label>
          
            
            
                          
                    
            
          </div>
          </form>
                <div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p>An Confirmation Email has been sent on your account</p>
                <p class="text-warning"><small></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default closeButton" data-dismiss="modal">Close</button>
                
            </div>
        </div>
    </div>
 
</div>   
                      
            
                                 </div>
                          
          </div>
          
          <div></div>
          
        </div>
        <div class="modal-footer" style=" padding-top:2px !important;">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>  
  
  </body></html>