<?php 
 $url = $this->url('home',array(),array('force_canonical' => true));
if (defined('RUNNING_FROM_ROOT')) {
  
	$url = $this->basePath().'/public';
} ?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(''. $this->translate('Hello42'))->setSeparator(' - ')->setAutoEscape(false) ?><?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome</title>
       
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $url . '/img/favicon.ico'))
            ->prependStylesheet($url . '/css/updatedstyle.css')
            ->prependStylesheet($url . '/css/jquery-ui.css')
            ->prependStylesheet($url . '/css/styleB.css')
            ->prependStylesheet($url . '/css/newcss.css')
                        ->prependStylesheet($url . '/css/style.css')
            		->prependStylesheet($url . '/css/responsive.css')
            		->prependStylesheet($url . '/css/main.css')
                        ->prependStylesheet($url . '/css/animate.min.css')
                        ->prependStylesheet($url . '/css/font-awesome.min.css')
                        ->prependStylesheet($url . '/css/bootstrap.min.css')
            //->prependStylesheet($url . '/css/jquery-ui-timepicker-addon.css')
            //->prependStylesheet($url . '/css/kendo.common.css')
            ->prependStylesheet($url . '/css/kendo.material.css')
            ->prependStylesheet($url . '/css/kendo.common-material.css')
            ->prependStylesheet($url . '/css/jquery.tooltip.css');
            
    ?>
        
    <?php  echo  $this->headScript()
            ->prependFile($url . '/js/jquery.tooltip.js')
            ->prependFile($url . '/js/kendo.all.js')
             //->prependFile($url . '/js/kendo.calendar.min.js')
             //->prependFile($url . '/js/jquery-ui-timepicker-addon.js')           
            ->prependFile($url . '/js/custom.js')
            ->prependFile($url . '/js/jquery-ui.js')
            ->prependFile($url . '/js/wow.min.js')
            ->prependFile($url . '/js/bootstrap.min.js')
            ->prependFile($url . '/js/jquery-2.js')
            ->prependFile($url . '/js/analytics.js')
            ->prependFile($url . '/js/jquery-1.11.2.min.js')
            ->prependFile($url . '/js/main.js')
            ->prependFile('http://maps.google.com/maps/api/js?sensor=true');
       
    ?>
       
</head>

<body class="homepage">

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +0123 456 70 90</p></div>
                    </div>
                    <div class="col-sm-8">
                       <div class="social">
                            <ul class="social-share">
                            
                            <li><a id="modal_trigger" href="#modal"  style="padding:0 10px;"><i class="fa fa-home fa-fw fa-1x"></i>  Home</a></li>
                            <li><a id="model_triger1" href="#modal" style="padding:0 10px;"><i class="fa fa-paper-plane fa-fw fa-1x"></i>  Services</a></li>
                            
                            
                                <li><a href="#"><i class="fa fa-user fa-fw fa-1x"></i>  Fare Structure</a></li>
                                <li><a href="#"><i class="fa fa-phone fa-fw fa-1x"></i>  Contact Us</a></li>
                                <li><a href="#"><i class="fa fa-user fa-fw fa-1x"></i>  Driver Registration</a></li> 
                           
                            </ul>
                            
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

      
            <div class="container">
                <div class="navbar-header col-sm-6 padding0 padding12top">
                    
                    <a class="navbar-brand" href="index.html"><img src="/images/logo.png" alt="logo"></a>
                </div>
				
                <div class="col-sm-6 padding0">
                
                <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-new-login" style="margin-top:5px; float:right;"> 
<!--<a href="/login" class="bgnone  pull-right">-->
<a data-toggle="modal" data-target="#myModallsogin" href="#" class="bgnone  pull-right center" >
  <div  class="circle-tile-heading login_signbg red marginbtom0"><i class="fa fa-sign-in fa-fw fa-1_5x sicon" style="cursor:pointer;" ></i></div>
  <label class="control-label textlogin">
  <!--<span id="login_user"></span>-->
  <span id="">Login</span>
  </label>
  </a> <a href="/login/index/signup" class="bgnone  pull-right center">
  <div onclick="signuphome();" class="circle-tile-heading login_signbg red marginbtom0"><i class="fa fa-user fa-fw fa-1_5x sicon" style="cursor:pointer;" ></i></div>
  <label class="control-label textlogin">
  <!--<span id="user_signup"></span>-->

<span id="">SignUp</span>
</label>
  </a> </div>
                
                </div>
            </div><!--/.container-->
        <!--/nav-->
		
    </header>
    
    <!--/header-->

   <div>
   	
   </div>
   <section id="screen1">
   <nav class="navbar navbar-inverse topbar " role="banner" style="background:#3e3c3c;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                </div>
				
                <div class="collapse navbar-collapse navbar-left padding0">
                    <ul class="nav navbar-nav ">
                        <li class="active"><a href="index.html"><i class="fa fa-home fa-6"></i></a></li>
                        <li><a href="#modal_flightandhotel" class="modal_flaghtandhotelsearch">About Us</a></li>
                         <li><a href="local-booking.html">Local Hire</a></li>
                        
                        <li><a href="pointtopoint-booking.html" class="active">Point to Point</a></li>
                       
                        
                         <li>
                            <a href="transfer.html" class="">Airport Transfer</a>
                           
                        </li>
                         <li >
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Packages </a>
                            
                        </li>
                                           
                    </ul>
                </div>
            </div><!--/.container-->
        </nav>
        
        </section>
</div>
