 <div class="col-md-3 banner-bottom-grid widthpercent20" style="float:right;">
                
                <div class="top-destinations-grids" style="margin-top:0;">
						
						<div class="top-destinations-bottom padding_margin0">
							<div class="td-grids">
                            
                            
                            <div class="left-div-form" style="border-bottom:1px solid #333;">
							<h4>Payment Detail</h4>
						</div>
                        
                      	  <div class="infopay">
                          <div class="left-div-form">
	<div class="title">Booking Amount</div>
			<div class="price">
		  		 
		  <span class=""><span class="WebRupee"> &#x20b9; </span></span><span class="paybooking">19600</span>
		</div>
        </div>
		<div class="left-div-form">
		<div class="title">Addon Amount</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> &#x20b9; </span></span><span class="payaddon">0</span></div>
</div>
<div class="left-div-form">
	<div class="title">Total Amount</div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> &#x20b9; </span></span><span class="payamount">19600 </span></div>
	</div>	
		<div class="clear"></div>
<div class="left-div-form">
		<div class="title" style="color:#C22815; font-weight:bold" title="Only for booking amount">Discount(10%)</div>
		<div class="price" style="color:#C22815; font-weight:bold" title="Only for booking amount"><span class="WebRupee"> &#x20b9; </span><span class="discount">1960</span> </div>
</div>
<div class="left-div-form">
		<div class="title">Net Amount</div>
		<div class="price"><span class="WebRupee"> &#x20b9; </span><span class="netamnt">17640</span> </div>
</div>
<div class="left-div-form">
		<div class="title">Service Tax(<span id="st_text">4.94</span>%)</div>
		<div class="price"><span class="WebRupee"> &#x20b9; </span><span class="payservice">872</span> </div>
		</div>
		<div class="clear"></div>
        <div class="left-div-form">
		<div class="title">Payable Amount</div>
		<div class="price"><span class="WebRupee"> &#x20b9; </span><span class="paytotal">18512</span><span id="usdvalue"></span> </div>
        </div>
        <div class="left-div-form">
         <label class="radio-inline specs" style="padding-left:0 !important; width:100%;">
        <div class="radioWrap">
          <input type="text" name="coupan_code" placeholder="Coupan Code" style="height:34px;" id="coupan_code" onClick="">
          </div>
          <div class="pull-right">
		  <label id="apply_coupancode" style="float:right; padding-right:0;"><a href="#" > Apply</a></label>
          </div>
		  <div id="coupan_msg"></div>
		  <div id="coupan_disount"></div>
        <small id="booklater_conditions_local"></small>
        </label>
        </div>
         <div class="left-div-form">
           
        <div class="title"><span class="WebRupee"><b>Total Charge</b></span></div>
	<div class="price"><span class="WebRupee"><span class="WebRupee"> Rs. </span></span><span class="payaddon">7548</span></div>
         </div>
         
          <div class="left-div-form">
          <div class="title">
        	<input type="checkbox" style="height:auto; margin:0 10px 0 0;"> 
        </div>
        <div class="title">
        Terms & Conditions   
        </div>
         </div>
         
         
          <div class="left-div-form">
         <div class="title" style="width:100%;"> 
   <!-- <div class="overviueimg31"><a href="travel.html" class="guestlogin">As a Guest</a></div>
    <div class="overviueimg32">or</div>
    <div class="overviueimg31"><a href="#" class="aslogin">As login</a></div>-->
    
    <div class="overviueimg31" style="width:100%; margin-top:2px;"><a href="outstation_Sightseeing.html" class="guestlogin">continue</a></div>
    
    <div></div>
    
    </div>
    
     <div class="title" style="width:100%; margin-top:5px;" align="center"> 
	 <div>
        

     
     </div>

		
							  </div>   
        
         </div>
        
     
</div>
                      
								<div class="clearfix"> </div>
							</div>
							
						</div>
					</div>
					
				</div>