<?php

if($this->flashMessenger()->hasCurrentSuccessMessages()){
    $flashMessage = $this->flashMessenger()->getSuccessMessages();
    
}else if($this->flashMessenger()->hasCurrentErrorMessages()){
    $flashMessage =  $this->flashMessenger()->getErrorMessages();
    
} else if($this->flashMessenger()->hasCurrentInfoMessages()){
    $flashMessage = $this->flashMessenger()->getInfoMessages();
    
} 
if (count($flashMessage)) :
    ?>
<ul>
    <?php 
        foreach ($flashMessage as $msg) : 
            foreach ($msg as $type => $message) :
    ?>
        <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li>
    <?php endforeach; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php if(isset($this->messages)) : ?>
<ul>
    <?php foreach ($this->messages as $type => $msg) : ?>
    <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
