<section id="recent-works" class="padding12top padding5topbot">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Our Features</h2>
                
            </div>

            <div class="row fadeInDown" align="center">
                <div class="col-xs-12 col-sm-4 col-md-4 homefrature fadeInDown">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/reliability.png" alt="" style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Reliability</a> </h3>
                                <ul>
                                	<li> Punctual Drivers</li>
                                    <li> Cars availablity surety</li>
                                    <li>Good quality cars</li>
                                     <li>Well groomed drivers</li>
                                     <li>24 x 7 support</li>
                                    
                                </ul>
                           
                               
                            </div> 
                        </div>
                    </div>
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/CONVIENCNE.png" alt=""  style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Convenience</a></h3>
                                 <ul>
                                	<li> Book by Call, Web or App</li>
                                    <li> Book in Cdvannce or Instant</li>
                                    <li>Pay by Cash or Card</li>
                                     <li>Online tracking of Ride</li>
                                     <li>24 x 7 support</li>
                                     
                                  
                                    
                                </ul>
                                
                            </div> 
                        </div>
                    </div>
                </div> 

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/SAFETY.png" alt=""  style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Safety </a></h3>
                                <ul>
                                	<li> Cab fitted with Panic button</li>
                                    <li> Real Time Cab Tracking</li>
                                    <li>Police verified Drivers</li>
                                     <li>24 x 7 support</li>
                                   
                                 
                                    
                                </ul>
                                
                            </div> 
                        </div>
                    </div>
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/OUR-FLEET.png" alt=""  style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Our Fleet </a></h3>
                                <ul>
                                	<li> Well maintained cars</li>
                                    <li> Well groomed drivers</li>
                                    <li> All types of car</li>
                                     <li>All amenities of comfort</li>
                                      
                                  
                                    
                                </ul>
                            </div> 
                        </div>
                    </div>
                </div>   
                
                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/OURCHAUFFER.png" alt=""  style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Our Chauffeur</a></h3>
                               <ul>
                                	<li> Police verified drivers</li>
                                    <li> Well groomed</li>
                                    <li> Trained in Health & Security</li>
                                                                         
                                </ul>
                               
                            </div> 
                        </div>
                    </div>
                </div>   

                <div class="col-xs-12 col-sm-4 col-md-4 homefrature">
                    <div class="recent-work-wrap">
                        <img class="img-responsive" src="/images_home/PRICING.png" alt=""  style="height:161px !important">
                        <div class="overlay">
                            <div class="recent-work-inner" align="left">
                                <h3><a href="#">Our Pricing</a></h3>
                               <ul>
                                	<li> Transparent pricing structure</li>
                                    <li> No extra charge for luggage</li>
                                    <li>No AC or Night charges</li>
                                    <li>No booking charges or Base fare</li>
                                  
                                    
                                </ul>
                            </div> 
                        </div>
                    </div>
                </div> 
  
            </div>
        </div>
    </section>
    
     <section id="partner">
        <div class="container" style="margin-bottom:10px;">
            <div class="center wow fadeInDown">
                <h2>Hello42 Cabs</h2>
                <p class="lead">Hello42 Cabs is a one-stop-shop for taxi booking services enabling the traveler to book safe and comfortable ride.<br />
                It gives you a wide range of choices between chauffeur driven car rentals and radio taxis across India to suit your specific need whether it be an airport transfer, late night travel, Outstationed Business meeting, An Outstation road trip or a special car on a special occasion. <br /> It lays on the following pillars : 
                
                </p>
            </div>      
           
                
        </div><!--/.container-->
    </section>
 
   
    
   <section id="conatcat-info">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="pull-left">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="media-body">
                            <h2>Have a question or need a custom quote?</h2>
                            <p>Our team is here to help 24 hours a day, 7 days a week. +91-11 424 242 42

</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.container-->    
    </section>