<?php
use Zend\Session\Container;
$user_session = new Container('User');
?>
<section id="main_form" class="padding12top" style="margin-top:20px">
               
    <div class="container">
        
<!-- Start for flash messages ---->
<?php echo $this->partial('point-to-point/index/flash-message.phtml'); ?> 

<!-- End for flash Messages--->
                            <div class="slide-margin">
                            <div class="col-sm-8">
                                 <div class="search-tabs search-tabs-bg search-tabs-nobox search-tabs-lift-top">
                <div class="tabbable">
                    
                    <div class="tab-content1">
                    
                        <div class="tab-pane fade in active" id="pointtopoint_form">
                           <label><h2 style="margin-top:0;">Point to Point Booking</h2></label>
                           <span id="location"></span>
                            <?php
                            /**
                             * 
                             */                                                        
                            
          $status = 0;
          $form = $this->form;
          //$form->setAttribute('action', $this->url('pointtopoint', array('action' => 'point')));
          
          $form->prepare();
          echo $this->form()->openTag($form);
          ?>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group form-group-lg form-group-icon-left">
                                                    <label>I want a Cab in*</label>
                                           
                                           <div class="select-style">
                                           	
                                               <?php echo $this->formElement($form->get('pointCabIn'));?>
                                            </div>
                                          
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input-daterange" data-date-format="M d, D">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group form-group-lg form-group-icon-left form-group-filled">
                                                     <label>Pickup Area*</label>
                                                        <?php echo $this->FormElement($form->get('term'));?>
                                                        <?php echo $this->FormElement($form->get('pointPickupArea_value'));?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group form-group-lg form-group-icon-left">
                                                     <label>Drop Area*</label>
                                                        <?php echo $this->FormElement($form->get('pointDropArea'));?>
                                                     <?php echo $this->FormElement($form->get('pointDropArea_value'));?>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-12">
                                        <div class="form-group form-group-lg form-group-icon-left"><!--<i class="fa fa-map-marker input-icon"></i>-->
                                                    <label>Pickup Address</label>
                                                    <?php echo $this->FormElement($form->get('pointAddress'));?>
                                                    
                                                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBiFNtCEUrKPHbCUOdqVKMCsq9-uPB5sc4&libraries=places" async defer></script> 
        <script>
          
            function initPTPMap() {
                var options = {
                componentRestrictions: {country: "in"},
                //types: ['address']
                };

                var input = document.getElementById('pointAddress');
                var autocomplete = new google.maps.places.Autocomplete(input,options);
            }
            
            google.maps.event.addDomListener(window, 'load', initPTPMap);
            </script>
                                                         
                                           
                                            
                                            </div>
                                    </div>
                                    
                                    <div class="col-sm-12 padding0">
                                    	 <div class="col-md-7">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                        <span> <?php echo $this->FormElement($form->get('pickup'));?></span> 
                                                       
                                                       
                                                    </div>
                                                </div>
                                                                                                
                                                <div class="col-sm-1 padding0" id="datetime" style="float:left; display:none;">
                                                <div class="col-md-8">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                                                                              
                                                        <?php echo $this->FormElement($form->get('pointLaterDate'));?>
                                                        
                                                    </div>
                                                </div>
                                                
                                                
                                    </div>
                                    
                                    <div class="col-sm-12 padding0">
                                    	 <div class="col-md-3">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                       <label>No. of Adults</label>
                                                        
                                                        <div class="select-style">
                                                            <?php echo $this->formElement($form->get('pointAdults'));?>
                                                        </div>                                                        
                                                       
                                                    </div>
                                                </div>
                                                
                                                <div class="col-md-3">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                       
                                                        <label>No. of Children</label>
                                                        
                                                        <div class="select-style">
                                                            <?php echo $this->formElement($form->get('pointChilds'));?>
							</div>
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                       
                                                        <label>No. of Luggages</label>
                                                        
                                                         <div class="select-style">
                                                             <?php echo $this->FormElement($form->get('pointLuggages'));?>
															
							</div>
                                                        
                                                    </div>
                                                </div>
                                                
                                                <div class="col-md-3">
                                                    <div class="form-group form-group-lg form-group-select-plus">
                                                       
                                                        <label>No of Cars *</label>
                                                        
                                                        <div class="select-style">
                                                          <?php echo $this->FormElement($form->get('pointCars'));?>  
                                                        
                                                        </div>
                                                        
                                                    </div>
                                                </div>
                                                
                                    </div>
                                    
                                    <div class="col-sm-12 padding0">
                                    	 <div class="col-md-6">
                                                    <div class="form-group-lg form-group-select-plus">
                                                       <label><?php echo $this->FormElement($form->get('agreeterms'));?></label>
                                                                                                               
                                                         Accept the Terms and Conditions
                                                                                                                
                                                       
                                                    </div>
                                                </div>
                                           </div>
                                    
                                </div>
                           
                           <?php echo $this->FormElement($form->get('submit'));?>
                                
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                        
                        
                        </div>
                        
                        
                        
                    </div>
                </div>
            </div>
            
                            </div>
                            
 						<div class="col-sm-4 tab-content1">
                                
                                <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
     
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/images/ads/1.jpg" alt="" width="100%" >
      </div>

      <div class="item">
        <img src="/images/ads/2.jpg" alt="" width="100%" >
      </div>
    
      <div class="item">
        <img src="/images/ads/3.jpg" alt="" width="100%" >
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
            
                            </div>
                            

                        </div>
                        
     </section>           
                    
   
    
    
    
    
 <!--/#theam-->
 
   
  <section id="recent-works" class="padding12top padding5topbot">
        <div class="container">
            <div class="center wow fadeInDown">
                <h2>Tarif for Point To Point</h2>
                
            </div>
            
            
            <div class="col-md-12 table-responsive">
      <h3  class="localfarebgstation">Fare Structure</h3>
      <table class="table table-hover table-striped" id="bootstrap-table"  style="border:1px solid #ddd">
        <tr>
          <th align="center">Car Type</th>
          
          <th align="center">Price / KM</th>
          <th align="center">Beyond / KM</th>
          <th align="center">Charges / Min</th>
          <th align="center"></th>
        </tr>
        <tr>
          <th  width="10%"  height="30" align="center" valign="top" style="border:1px solid #ddd">Economy <br>
            <img alt="" class="localimg" src="/images/economycar.png"> </th>
          
          <th align="center"><i class="fa fa-inr"></i> 100/5KM</th>
          <th align="center"><i class="fa fa-inr"></i> 12/KM</th>
          <th align="center"><i class="fa fa-inr"></i> 0.00/Min</th>
          <th align="center"><a onclick="booking_local();" id="" role="button" class="btn btn-primaryred btn_fare" href="#topheader">Book</a> </th>
        </tr>
        <tr>
          <th rowspan="2"  width="10%"  height="30" align="center" valign="top" style="border:1px solid #ddd">Sedan <br>
           
             <img src="/images/sedancar.png" class="localimg" alt=""> 
            
            </th>
          
        </tr>
        <tr>
         
          <th align="center"><i class="fa fa-inr"></i> 100/4KM</th>
          <th align="center"><i class="fa fa-inr"></i> 15/KM</th>
          <th align="center"><i class="fa fa-inr"></i> 0.00/Min</th>
          <th align="center"> <a onclick="booking_local();" id="" role="button" class="btn btn-primaryred btn_fare" href="#topheader">Book</a> </th>
        </tr>
        <tr>
          <th rowspan="2"  width="10%"  height="30" align="center" valign="top" style="border:1px solid #ddd">Prime <br>
           <img src="/images/primecar.png" class="localimg" alt="">  </th>
        
        </tr>
        <tr>
          
          <th align="center"><i class="fa fa-inr"></i> 250/10KM</th>
          <th align="center"><i class="fa fa-inr"></i> 25/KM</th>
          <th align="center"><i class="fa fa-inr"></i> 0.00/Min</th>
          <th align="center"> <a onclick="booking_local();" id="" role="button" class="btn btn-primaryred btn_fare" href="#topheader">Book</a> </th>
        </tr>
        </table>
    </div>
           
        </div>
    </section>
    
     <section id="partner">
        <div class="container" style="margin-bottom:10px;">
            <div class="center wow fadeInDown">
                <h2>Hello42 Cabs</h2>
                <p class="lead">Hello42 Cabs is a one-stop-shop for taxi booking services enabling the traveler to book safe and comfortable ride.<br />
                It gives you a wide range of choices between chauffeur driven car rentals and radio taxis across India to suit your specific need whether it be an airport transfer, late night travel, Outstationed Business meeting, An Outstation road trip or a special car on a special occasion. <br /> It lays on the following pillars : 
                
                </p>
            </div>    
                            
        </div><!--/.container-->
    </section>
     
   <section id="conatcat-info">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="pull-left">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="media-body">
                            <h2>Have a question or need a custom quote?</h2>
                            <p>Our team is here to help 24 hours a day, 7 days a week. +91-11 424 242 42

</p>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/.container-->    
    </section>
 
 <script>
 $(document).ready(function(){
   
    $("#pointPickupArea").autocomplete({
        source: function(request, response) {
            $.ajax({
                url: '<?php echo $this->url('default', array('action'=>'location')); ?>',
                dataType: "json",
                type: "POST",
                data: {
                    term : request.term,
                    city : $("#pointCabIn").val()
                },
                success: function(data) {
                    response(data);
                }
            });
        },
        min_length: 3,
        delay: 300,
        
      //source: site_url+'/tunnel/menu/allcities2?key='+API_KEY,minLength:0,delay:0,
      focus: function( event, ui ) {		 
        $( "#pointPickupArea" ).val( ui.item.label );
        return false;
      },
      select: function( event, ui ) {
        $( "#pointPickupArea" ).val( ui.item.label );
        $( "#pointPickupArea_value" ).val( ui.item.value );
        
        return false;
      }
    });
    
    $("#pointDropArea").autocomplete({
        source: function (request, response) {
            $.ajax({
                url:'<?php echo $this->url('default', array('action'=>'location')); ?>',
                dataType: "json",
                type: "POST",
                data: {
                    term: request.term,
                    city: ''
                },
                success: function (data) {
                    response(data);
                }
            });
        },
        min_length: 3,
        delay: 300,
        focus: function (event, ui) {
            $("#pointDropArea").val(ui.item.label);
            return false;
        },
        select: function (event, ui) {
            $("#pointDropArea").val(ui.item.label);
            $("#pointDropArea_value").val(ui.item.value);


            return false;
        }
    });
    });
        
    </script>
    
  <script>
  $(document).ready(function () {

    $("#pointtopoint").validate({
        
        rules: {
            pointCabIn: {
                required: true
            },
            term:{
                required:true
            },
            pointDropArea:{
                required:true
                        
                    },
            agreeterms:{
                required:true
            }        
        },
        messages: {
            pointCabIn: {
                required: "Please Select City Name"
            }
        },
        submitHandler: function (form) { 
            form.submit();
        }
    });

});
  </script>
  
  // for current address location
  
  <script>
$(document).ready(function(){
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showLocation);
    } else { 
        $('#location').html('Geolocation is not supported by this browser.');
    }
    
    function showLocation(position) {    
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
    $.ajax({
        type:'POST',
        dataType:'html',
        url:'<?php echo $this->url('default', array('action'=>'ajaxGetCurrentLocation')); ?>',
        data:{ latitude:latitude,longitude:longitude },
        success:function(msg){
            if(msg){
               $("#location").html(msg);
            }else{
                $("#location").html('Not Available');
            }
        }
    });
}
});


</script>
  
  
  