<!--/#main-slider-->
    
   <div class="container-fluid navbar-inverse mannavi navbar-navnew" style="height:41px !important;" >
  <div class="container" style="padding:0 10px;">
    <div class="navbar navbar-inverse marginbtom0 mannavi" role="navigation" style="border-radius:0; border:none; z-index:1; height:auto;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" style="padding:0;" data-toggle="collapse" data-target=".navbar-collapse2"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
   <div class="navbar-collapse2 collapse" style="padding:0;">
   <div class="row">
   
   <div class="col-sm-2"><a href="" id="" style="text-transform: capitalize; line-height:40px; font-size:16px !important; padding-left:40px;" class="navbar-navlink"  data-toggle="modal" data-target="#myModalprintsmscancle">Track Car</a><i class="fa fa-car fa-fw fa-1_5x sicon" style="cursor:pointer; color:#FFF; margin-top:0; position:absolute;"></i></div>
   <div class="col-sm-3"><a href="" id="" style="text-transform: capitalize; line-height:40px; font-size:16px !important; padding-left:40px;" class="navbar-navlink"  data-toggle="modal" data-target="#myModalprintsmscancle">Print/SMS Ticket</a><i class="fa fa-print fa-fw fa-1_5x sicon" style="cursor:pointer; color:#FFF; margin-top:0; position:absolute;"></i></div>
   <div class="col-sm-2"><a href=""  id="" style="text-transform: capitalize; line-height:40px; font-size:16px !important; padding-left:40px;" class="navbar-navlink" data-toggle="modal" data-target="#myModalprintsmscancle">Cancel Ticket</a><i class="fa fa-times fa-fw fa-1_5x sicon" style="cursor:pointer; color:#FFF; margin-top:0; position:absolute;"></i></div>
   <div class="col-sm-2"><a href="" id="" data-toggle="modal" data-target="#myModalprintsmscancle" class="navbar-navlink" style="text-transform: capitalize; line-height:40px; font-size:16px !important; padding-left:40px;">Refund Status</a><i class="fa fa-exchange fa-fw fa-1_5x sicon" style="cursor:pointer; color:#FFF; margin-top:0; position:absolute;"></i></div>
   <div class="col-sm-2"><a href="" data-toggle="modal" data-target="#myModalfeedbackss" class="navbar-navlink" id="" style="text-transform: capitalize; line-height:40px; font-size:16px !important; padding-left:40px;">Give Feedback</a><i class="fa fa-envelope fa-fw fa-1_5x sicon" style="cursor:pointer; color:#FFF; margin-top:0; position:absolute;"></i></div>
   
   </div>
       
      </div>
      <!--/.nav-collapse --> 
    </div>
  </div>
</div> 